#客户端
#企业微信开发配置（要改）
weixin:
  #企业ID
  CorpID: wwa28fc945896a74b9
  #部门ID（获取企业号 制定部门下的所有的用户）
  department_id: 1
  #应用0 ID
  app0:
    agentid: 1000002
    #应用0Secret
    Secret: HK4yUVvsWkKx-lX4WZIWczLt2J2cnB-IU5Vd8LaKk5w
    #应用0 消息ID
    message:
      #应用0 接收消息服务器Token
      sToken: DtdR0qmjomHnMJbXJiOIWch85
      #应用0 接收消息服务器EncodingAESKey
      sEncodingAESKey: QtJHsTBM9GEFlVCYeteo9KbZmterPTEFHKBmOnBzuXj
#接口上传文件大小限制
spring:
  http:
    multipart:
      max-file-size: 300MB
      max-request-size: 600MB
#FS（要改）
share:
  commonfs:
    #本机ip
    local_ip: 192.168.2.100
    #文件存储类型，有分布式存储DFS，JavaApi的本地存储JFS,可以不配置，默认使用DFS
    file_server_type: HDFS
    #dfs服务器实际服务器ip地址
    file_server_dfs_real_ip: 192.168.1.235
    #dfs服务器代理IP地址-光盾映射后的外网访问地址，重庆用的参数，没有代理的请放空或者跟file_server_dfs_real_ip一致即可
    file_server_dfs_proxy_ip: 192.168.1.235
    #dfs服务器端口
    file_server_dfs_port: 1314
    #jfs保存文件的本机路径，当使用JFS时候需要配置此值
    file_server_jfs_path: /opt/JFS
    #文件限制大小 默认100M 单位KB
    file_limit_size: 1048576000
    #HDFS的hadoopUri
    hadoopUri: hdfs://192.168.0.50:9000
    #HDFS的hadoopAccount
    hadoopAccount: root
    #share.commonfs.hdfs的配置-默认备份数设置2
    hdfsReplication: 2
    #hdfs的配置-默认备block的大小设置64M
    hdfsBlocksize: 64M
    #hdfs的其他参数配置-json串
    hdfsExtProp:
#（要改）
#足迹圈-APPID
zjq_appid: 82fa13e53ff711e99a7700163e00414a
#足迹圈-sdk发送方式 有body、xml、rest、自定义参数等
zjq_sdk_type: rest
#足迹圈-sdk配置的编码前缀
zjq_sdk_code: zjq_sdk

#（要改）
#项目系统前缀（暂时‘分享’,'项目详情二维码分享'在用） 注意最后要加/
project_url: http://127.0.0.1:8080/springbootdemo/

#======在Linux下需要配置  ffmpeg 命令文件目录（用于音视频转换）start ===========#
file_conversion_path: /opt/ffmpeg/bin目录
#在Linux下音频文件转换为mp3文件命令
command_amrTomp3: ffmpeg -y -i {0} -acodec libmp3lame -ab 128000 -ac 2 -ar 44100 {1}
#在Linux下转换视频文件转换为mp4文件命令
command_toMp4: ffmpeg -y -i {0} -vcodec copy -acodec copy {1}
#======在Linux下需要配置  ffmpeg 命令文件目录（用于音视频转换）end ===========#

#每5分 0 0/5 * * * ?
#每10s 0/10 * * * * ?
audioDownload:
  schedule: 0 0/5 * * * ?

#缓存目录配置
localTempDir: /opt/lesson/temp1